name: Go func tests

env:
  cc_id: "21be1cdc42d49f616e915dd75a0de895095dc7db7b87ebf732b8e0035d9cbcb5"
  code_dir: "mainpkg"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ env.cc_id }}
        with:
          coverageCommand: go test ./... -coverprofile=c.out
          debug: true
          prefix: github.com/Ryo-not-rio/grapi